#!/bin/sh
if [ "${SIM_UID:-$(getprop sim.uid)}" = 0 ]; then
    echo "uid=0(root) gid=0(root) context=u:r:su:s0"
else
    echo "uid=2000(shell) gid=2000(shell) groups=1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats) context=u:r:shell:s0"
fi
